server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false
servers:
  - www.bookstore.test.com

---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - www.bookstore.com