#Server port by default 8081
server:
  port: 8081

#Configuration profiles

#Test profile
---
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
enabled: false
servers:
  - www.bookstore.test.com

#Production profile
---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
enabled: true
servers:
  - www.bookstore.com

#Development profile
---
spring:
  config:
    activate:
      on-profile: dev
name: dev-YAML
environment: development
enabled: true
servers:
  - www.bookstore.dev.com

#Database connection
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/bookstorage?&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

